# Generated by Django 4.1 on 2022-08-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_book_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["last_name", "-date_of_birth"],
                "verbose_name": "Авторы",
                "verbose_name_plural": "Авторы",
            },
        ),
    ]
